#!/bin/bash

TEST_API="enabled"
DATABASE_URL=
JWT_SECRET="E9ql4cmZzDNG9qL8xh6F"
MAIL_PROVIDER=
MAIL_ADDR=
MAIL_PASSWD=
LOCAL="enabled"
PORT=12345
HOST="localhost:${PORT}/v1"
MIN_USER_NUMBER=2


TEST_API=$TEST_API DATABASE_URL=$DATABASE_URL JWT_SECRET=$JWT_SECRET MAIL_ADDR=$MAIL_ADDR MAIL_PASSWD=$MAIL_PASSWD LOCAL=$LOCAL PORT=$PORT HOST=$HOST MIN_USER_NUMBER=$MIN_USER_NUMBER MAIL_PROVIDER=$MAIL_PROVIDER  node app.js
